name: Pull Requests

on:
  push:
    branches-ignore:
      - "main"
      - "master"
      - "development"
      - "releases/v*"
  pull_request:
    branches:
      - "releases/v*"
      - development

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  # Format PR
  format_check:
    name: Checks Source Code Formatting
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup CommandBox CLI
        uses: Ortus-Solutions/setup-commandbox@v2.0.1

      - name: Install pinned formatter
        run: box install commandbox-cfformat@0.21.0

      - name: Check formatting
        run: box run-script format:check
