name: Build a Release

on:
  # If you push to master|main this will trigger a stable release
  push:
    branches:
      - master
      - main

  # Reusable workflow : Usually called by a `snapshot` workflow
  workflow_call:
    inputs:
      snapshot:
          description: 'Is this a snapshot build?'
          required: false
          default: false
          type: boolean

env:
  MODULE_ID: sentry
  SNAPSHOT: ${{ inputs.snapshot || false }}

jobs:
  ##########################################################################################
  # Build & Publish
  ##########################################################################################
  build:
    name: Build & Publish
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup CommandBox
        uses: Ortus-Solutions/setup-commandbox@v2.0.1
        with:
          forgeboxAPIKey: ${{ secrets.FORGEBOX_TOKEN }}

      - name: "Setup Environment Variables For Build Process"
        id: current_version
        run: |
          echo "VERSION=`cat box.json | jq '.version' -r`" >> $GITHUB_ENV
          box package set version=@build.version@+@build.number@
          # master or snapshot
          echo "Github Ref is $GITHUB_REF"
          echo "BRANCH=master" >> $GITHUB_ENV
          if [ $GITHUB_REF == 'refs/heads/development' ]
          then
            echo "BRANCH=development" >> $GITHUB_ENV
          fi

      - name: Update changelog [unreleased] with latest version
        uses: thomaseizinger/keep-a-changelog-new-release@1.3.0
        if: env.SNAPSHOT == 'false'
        with:
          changelogPath: ./changelog.md
          tag: v${{ env.VERSION }}

      - name: Build ${{ env.MODULE_ID }}
        run: |
          npm install -g markdownlint-cli
          markdownlint changelog.md --fix
          box install commandbox-docbox
          box task run taskfile=build/Build target=run :version=${{ env.VERSION }} :projectName=${{ env.MODULE_ID }} :buildID=${{ github.run_number }} :branch=${{ env.BRANCH }}

      - name: Commit Changelog To Master
        uses: EndBug/add-and-commit@v9.1.4
        if: env.SNAPSHOT == 'false'
        with:
          author_name: Github Actions
          author_email: info@ortussolutions.com
          message: 'Finalized changelog for v${{ env.VERSION }}'
          add: changelog.md

      - name: Tag Version
        uses: rickstaa/action-create-tag@v1.7.2
        if: env.SNAPSHOT == 'false'
        with:
          tag: "v${{ env.VERSION }}"
          force_push_tag: true
          message: "Latest Release v${{ env.VERSION }}"

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.MODULE_ID }}
          path: |
            .artifacts/**/*
            changelog.md

      - name: Upload Binaries to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: "downloads.ortussolutions.com"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          SOURCE_DIR: ".artifacts/${{ env.MODULE_ID }}"
          DEST_DIR: "ortussolutions/coldbox-modules/${{ env.MODULE_ID }}"

      - name: Upload API Docs to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: "apidocs.ortussolutions.com"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          SOURCE_DIR: ".tmp/apidocs"
          DEST_DIR: "coldbox-modules/${{ env.MODULE_ID }}/${{ env.VERSION }}"

      - name: Publish To ForgeBox
        run: |
          cd .tmp/${{ env.MODULE_ID }}
          cat box.json
          box forgebox publish --force

      - name: Create Github Release
        uses: taiki-e/create-gh-release-action@v1.8.0
        continue-on-error: true
        if: env.SNAPSHOT == 'false'
        with:
          title: ${{ env.VERSION }}
          changelog: changelog.md
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: refs/tags/v${{ env.VERSION }}

  ##########################################################################################
  # Prep Next Release
  ##########################################################################################
  prep_next_release:
    name: Prep Next Release
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    needs: [ build ]
    steps:
      # Checkout development
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: development

      - name: Setup CommandBox
        uses: Ortus-Solutions/setup-commandbox@v2.0.1
        with:
          forgeboxAPIKey: ${{ secrets.FORGEBOX_TOKEN }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.MODULE_ID }}
          path: .tmp

      # Copy the changelog to the development branch
      - name: Copy Changelog
        run: |
          cp .tmp/changelog.md changelog.md

      # Bump to next version
      - name: Bump Version
        run: |
          box bump --patch --!TagVersion

      # Commit it back to development
      - name: Commit Version Bump
        uses: EndBug/add-and-commit@v9.1.4
        with:
          author_name: Github Actions
          author_email: info@ortussolutions.com
          message: 'Version bump'
          add: |
            box.json
            changelog.md
